### ISSUE TITLE
http_transport_test_fixture.cc error

### ISSUE THREAD

**Issue by cagdasc** [google/google-api-cpp-client#17]
compile output:

`/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In member function 'virtual void googleapis::HttpTransportTestFixture_TestTimeout_Test::TestBody()':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:523:20: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
                    << " status=" << http_response->transport_status()
                    ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In function 'void googleapis::GatherAsyncResponse(int, googleapis::base::Mutex*, std::vector<googleapis::client::HttpRequest*>*, int*, googleapis::client::HttpRequest*)':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:762:45: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
   VLOG(1) << "*** Got Response for i=" << i << " status=" << response->status();
                                             ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In function 'void googleapis::VerifyAsyncResponse(int, int, googleapis::client::HttpRequest*)':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:781:45: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
   VLOG(1) << "*** Got Response for i=" << i << " status=" << response->status();
                                             ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
make[2]: *** [src/googleapis/client/CMakeFiles/googleapis_http_transport_test_fixture.dir/transport/test/http_transport_test_fixture.cc.o] Error 1
make[1]: *** [src/googleapis/client/CMakeFiles/googleapis_http_transport_test_fixture.dir/all] Error 2
make: *** [all] Error 2
Cagdass-MacBook-Pro:build cagdascaglak$ make all >> out.txt
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In member function 'virtual void googleapis::HttpTransportTestFixture_TestTimeout_Test::TestBody()':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:523:20: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
                    << " status=" << http_response->transport_status()
                    ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In function 'void googleapis::GatherAsyncResponse(int, googleapis::base::Mutex*, std::vector<googleapis::client::HttpRequest*>*, int*, googleapis::client::HttpRequest*)':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:762:45: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
   VLOG(1) << "*** Got Response for i=" << i << " status=" << response->status();
                                             ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc: In function 'void googleapis::VerifyAsyncResponse(int, int, googleapis::client::HttpRequest*)':
/Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:781:45: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
   VLOG(1) << "*** Got Response for i=" << i << " status=" << response->status();
                                             ^
In file included from /usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/iostream:39:0,
                 from /Users/cagdascaglak/Desktop/libsandbox/google-api-cpp-client/src/googleapis/client/transport/test/http_transport_test_fixture.cc:25:
/usr/local/Cellar/gcc48/4.8.4/include/c++/4.8.4/ostream:602:5: error:   initializing argument 1 of 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = googleapis::util::Status]'
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
make[2]: *** [src/googleapis/client/CMakeFiles/googleapis_http_transport_test_fixture.dir/transport/test/http_transport_test_fixture.cc.o] Error 1
make[1]: *** [src/googleapis/client/CMakeFiles/googleapis_http_transport_test_fixture.dir/all] Error 2
make: *** [all] Error 2`

**Comment by aiuto** [comment]
This is because of a mismatch of the type of Status in different environments.
If you really want to build the tests, work around it by deleting the CHECK and LOG statements the do not compile.
