### ISSUE TITLE
Service Account Support

### ISSUE THREAD

**Issue by navintestapi** [google/google-api-cpp-client#21]
Does the CPP Client API has provision for Service Accounts?

How do you integrate the Service Account implementation into the framework?

**Comment by aiuto** [comment]
Added at commit 12c5779eaacf2767da345bfced0a2ff82ae6b0a4

https://github.com/google/google-api-cpp-client/blob/master/src/googleapis/client/auth/oauth2_service_authorization.cc

It had accidentally been left out of a manifest file.

**Comment by navintestapi** [comment]
It requires googleapis/util/helpers.h and apiserving/clients/cpp/config.h which are not present.

Can you please add these files?

**Comment by navintestapi** [comment]
Perhaps they are not even required and can be commented out

**Comment by aiuto** [comment]
googleapis/util/helpers.h  is unneeded.
config.h should be #include "googleapis/client/config.h"
I'm updating that shortly

**Comment by navintestapi** [comment]
I'm trying to use the service Account Flow, bit it fails when trying to read the Client Secret file.

I call "OAuth2AuthorizationFlow::InitFromClientSecretsPath" and give the path of the Client Secret file but it fails in the call to "OAuth2AuthorizationFlow::InitFromJsonData" with the following error:

Json::Value& Json::Value:Operator[](const char*) const: Assertion `type_ == nullValue || type_ == objectValue' failed.

**Comment by navintestapi** [comment]
My Client secret file is like:

{
  "private_key_id": "XXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\nXXX\n-----END PRIVATE KEY-----\n",
  "client_email": "XXX@developer.gserviceaccount.com",
  "client_id": "XXX.apps.googleusercontent.com",
  "type": "service_account"
}

**Comment by navintestapi** [comment]
It seems that the JSON Reader fails because the format of the Service Account file is different to the installed and web applications JSON file, as the Service Account does not have a root element.

Looks like OAuth2AuthorizationFlow::SimpleJsonData::InitFromContainer should not be called for Service Account.

**Comment by navintestapi** [comment]
@aiuto : Any help on this?

**Comment by aiuto** [comment]
I can't offer any help on this. My day job is with a product team, not maintaining this SDK.
I think your best option is to ask the developer relations team for the specific APIs you are using. They have more resources to figure out a solution.
