### ISSUE TITLE
prepare_dependencies.py fails on glog

### ISSUE THREAD

**Issue by drcrallen** [google/google-api-cpp-client#22]
https://code.google.com/p/google-glog/issues/detail?id=203 occurred on my system while trying to compile glog dependency. `error: ‘ParseCommandLineFlags’ was not declared in this scope`

Patch at https://code.google.com/p/google-glog/issues/detail?id=203#c5 allowed `prepare_dependencies.py` to function

**Comment by aiuto** [comment]
So, that looks like a glog problem. Hand downgrade to an older version or upgrade to a fixed version and install it yourself.
You should hand install all of the dependencies yourself. Using prepare_dependencies.py is a crutch for trying to make the out-of-the-box demo quicker. For real products, you should be checking in all your dependencies to your revision control system.
