### ISSUE TITLE
Resumable uploads using MediaUploader class

### ISSUE THREAD

**Issue by harshaltalele** [google/google-api-cpp-client#23]
Hello,

I am looking to use MediaUpload class for uploading large attachments, upto 15 MB.

From source code I found out below mentioned text in googleapis/client/service/media_uploader.h.h file,
- TODO(user): The interface does not yet support
-   -- streaming content
-   -- resumable uploads
  *-- auto protocol selection

Is there any plan to include resumable download option in Media Uploader?

Or any other way to upload larger attachments while sending an email?

Thanks,
Harshal

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
