### ISSUE TITLE
Possibly unintended regression in service_apis

### ISSUE THREAD

**Issue by BoniLindsley** [google/google-api-cpp-client#25]
#### Problem

While compiling the provided sample for the Calendar API, I have noticed many undefined references while linking. They were to unimplemented member functions. For example, [Event::get_start()](https://github.com/google/google-api-cpp-client/blob/1d6289ece2b08f0ae3682f831f5a5a45a6d6962b/service_apis/calendar/google/calendar_api/event.h#L2404) in the current master is declared as:

```
const EventDateTime get_start() const;
```

Having looked through its corresponding source, it does not seem to be implemented at all.
#### Possible reason

There was a [commit (7edc848)](https://github.com/google/google-api-cpp-client/commit/7edc84885e49e1455a9654535b7c9116d1c578b3#diff-47ec7fdc39dc1eaa898e1cf83c1c8624L2380) on Jun 4, 2015 that had a possibly unintended side effect. What it did, in particular, was this:

```
-  const EventDateTime get_start() const {
-     const Json::Value& storage = Storage("start");
-    return client::JsonValueToCppValueHelper<EventDateTime >(storage);
-  }
+  const EventDateTime get_start() const;
```

It seems to have reverted the member function mentioned above. And this is done to many other member functions across a large number of classes. This explains the multitude of undefined references from linking.

Furthermore, by reverting to this commit in the directory

```
google-api-cpp-client/service_apis/calendar/google/calendar_api/
```

the sample compiled and ran just fine.
#### Possible fix

Looking at the [commits](https://github.com/google/google-api-cpp-client/commits/master/service_apis) in the `google-api-cpp-client/service_apis` directory, there are limited number of changes in it. It may be possible to fix this, by undoing the above commit and then reapplying the remaining 5. However, whether this should be done, depends on the originally intended changes made in the commit in question. I cannot tell what those were.

It may also have something to do with the google-apis-code-generator not acting on the right sources, of which I have little information on.

Another problem that comes to mind is whether this affects more APIs than the three included. This came to mind because the lastest source from

```
https://developers.google.com/resources/api-libraries/download/calendar/v3/cpp
```

is also affected.

**Comment by aiuto** [comment]
I can not reproduce that. There was a lot of churn recently and I just updated all the sample libraries in https://github.com/google/google-api-cpp-client/commit/c3c90ff5b5b6fde3c4a9aaf74dfca06c923ee41b

One thing to note is that there will be expected breakages w.r.t. StringPiece -> string over the next quarter, as we eliminate most public facing uses of StringPiece. That is, we might be able to keep the code generator in line with this project, but the served libraries will probably lag behind from time to time.

**Comment by steveniemitz** [comment]
+1, this is easily reproducible with the current generated services (not just those included as examples in this SDK), just attempt to link against any method that returns anything other than a primitive type on the generated models.

**Comment by BoniLindsley** [comment]
Included examples are working now.

I think regenerating calender API in a [May-2017 commit](https://github.com/google/google-api-cpp-client/commit/8cc0e1ceb99db67ce45ca2fa32aa822a2858040a#diff-aad54b237497c8d7fadb0e09e1a79a22R243) fixed it -- it restored the missing function implementations, at least for the one mentioned in the first post. ([Service API downloads](https://google.github.io/google-api-cpp-client/latest/available_service_apis.html) were possibly fixed much earlier, but I have no time machine on that one.) It was followed, five days later, by a ["refresh"](https://github.com/google/google-api-cpp-client/commits/32df00d90660e657a44955fad5c3718fce1a53c5/service_apis/calendar/google/calendar_api/event.cc) that made the `StringPiece` changes mentioned by the contributor.

A wild guess on what had happened is that implementations were moved out of header mid-2015. But code generators only picked up the changes to the header. And then due to the "breakages w.r.t. `StringPiece`", no further changes were made public until kinks were smoothed out and contributors have time. This would explain why the contributor saw a different snapshot than us.

Regardless, good to see that this was fixed, albeit indirectly. Thank you.
