### ISSUE TITLE
I can`t build to success fallowing this Error.

### ISSUE THREAD

**Issue by asjgi** [google/google-api-cpp-client#27]
I have to Explain the step by step .When i was to build.

  133  ./prepare_dependencies.py 
  134  ls
  135  mkdir build
  136  cd build/
  137  ../external_dependencies/install/bin/cmake ..
  138  make
First i have to fallowing this Error.

/home/david/workspace/src/google-api-cpp-client/src/googleapis/client/data/jsoncpp_data.cc: In member function ‘virtual googleapis::util::Status googleapis::client::JsonCppData::LoadFromJsonReader(googleapis::client::DataReader_)’:
/home/david/workspace/src/google-api-cpp-client/src/googleapis/client/data/jsoncpp_data.cc:64:46: error: ‘class Json::Reader’ has no member named ‘getFormattedErrorMessages’
     return StatusInvalidArgument(json_reader.getFormattedErrorMessages());
                                              ^
make[2]: *_\* [src/googleapis/client/CMakeFiles/googleapis_jsoncpp.dir/data/jsoncpp_data.cc.o] 
make[1]: **\* [src/googleapis/client/CMakeFiles/googleapis_jsoncpp.dir/all] 2
make: **\* [all] 2

I was correct the bad word ‘getFormattedErrorMessages- >‘getFormatedErrorMessages
  140  ls
  141  cd ..
  142  ls
  143  vi CMakeLists.txt 
  144  vi /home/david/workspace/src/google-api-cpp-client/src/googleapis/client/data/jsoncpp_data.cc
  145  cd build/
  146  make
[ 87%] Building CXX object src/samples/CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o
Linking CXX executable ../../bin/calendar_sample
/usr/bin/ld: cannot find -lgoogle_calendar_api
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/calendar_sample] 1
make[1]: **\* [src/samples/CMakeFiles/calendar_sample.dir/all] 2
make: **\* [all] 2
Second I was Correct the CMakefile in root dir.

OFF -> option(googleapis_build_service_apis "Build specialized service APIs." ON)
OFF -> option(BUILD_SHARED_LIBS "Build shared libraries (DLLs)." ON)

and Service_api/Cmakefile.txt
if(${dir} MATCHES "^([^/]_)//CMakeLists.txt")
-> if(${dir} MATCHES "^([^/]_)/CMakeLists.txt")

CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `googleapis::Display(std::string const&, google_calendar_api::Event const&)':
calendar_sample_main.cc:(.text+0x8ef): undefined reference to`google_calendar_api::Event::get_start() const'
calendar_sample_main.cc:(.text+0x924): undefined reference to `google_calendar_api::Event::get_start() const'
calendar_sample_main.cc:(.text+0x9bb): undefined reference to`google_calendar_api::Event::get_end() const'
calendar_sample_main.cc:(.text+0x9f0): undefined reference to `google_calendar_api::Event::get_end() const'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function`googleapis::CalendarSample::Startup(int, char*_)':
calendar_sample_main.cc:(.text+0xd6e): undefined reference to `googleapis::client::OAuth2AuthorizationFlow::MakeFlowFromClientSecretsPath(std::string const&, googleapis::client::HttpTransport_, googleapis::util::Status_)'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `googleapis::CalendarSample::Run()':
calendar_sample_main.cc:(.text+0x2659): undefined reference to`google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x26dc): undefined reference to `google_calendar_api::Event::mutable_end()'
calendar_sample_main.cc:(.text+0x28ba): undefined reference to`google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x293d): undefined reference to `google_calendar_api::Event::mutable_end()'
calendar_sample_main.cc:(.text+0x2b2f): undefined reference to`google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x2bc4): undefined reference to `google_calendar_api::Event::mutable_end()'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function`void googleapis::DisplayList<google_calendar_api::CalendarList, google_calendar_api::CalendarListEntry>(std::string const&, std::string const&, google_calendar_api::CalendarList const&)':
calendar_sample_main.cc:(.text._ZN10googleapis11DisplayListIN19google_calendar_api12CalendarListENS1_17CalendarListEntryEEEvRKSsS5_RKT_[_ZN10googleapis11DisplayListIN19google_calendar_api12CalendarListENS1_17CalendarListEntryEEEvRKSsS5_RKT_]+0xda): undefined reference to `google_calendar_api::CalendarList::get_items() const'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function`void googleapis::DisplayList<google_calendar_api::Events, google_calendar_api::Event>(std::string const&, std::string const&, google_calendar_api::Events const&)':
calendar_sample_main.cc:(.text._ZN10googleapis11DisplayListIN19google_calendar_api6EventsENS1_5EventEEEvRKSsS5_RKT_[_ZN10googleapis11DisplayListIN19google_calendar_api6EventsENS1_5EventEEEvRKSsS5_RKT_]+0xda): undefined reference to `google_calendar_api::Events::get_items() const'
collect2: error: ld returned 1 exit status
make[2]: *_\* [bin/calendar_sample] 1
make[1]: **\* [src/samples/CMakeFiles/calendar_sample.dir/all] 2
make: **\* [all] 2

**Comment by asjgi** [comment]
i was change that - MakeFlowFromClientSecretsPath -> MakeFlowFromClientSecretsJson Method.
And then i seen that Success Build

**Comment by asjgi** [comment]
i was change that - MakeFlowFromClientSecretsPath -> MakeFlowFromClientSecretsJson Method.
And then i saw that Success Build

**Comment by dgreatwood** [comment]
Hi asjgi -

Thanks for posting these workarounds, to get samples to compile. The only that didn't work when I tried was the last. To be more explicit, in src/samples/calendar_sample_main.cc, I replaced one instance of MakeFlowFromClientSecretsPath with MakeFlowFromClientSecretsJson.

The error message was unchanged (see below). Is there something else involved?

To take the first error first, there is a get_start (per google_calendar_api::Event::get_start) declared (but not defined) in event.h; the time_period.h get_start is defined and looks similar/same, but that is google_calendar_api::TimePeriod::get_start, not Event.

Thanks again.

CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `googleapis::Display(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_calendar_api::Event const&)':
calendar_sample_main.cc:(.text+0x998): undefined reference to `google_calendar_api::Event::get_start() const'
calendar_sample_main.cc:(.text+0x9d0): undefined reference to `google_calendar_api::Event::get_start() const'
calendar_sample_main.cc:(.text+0xa70): undefined reference to `google_calendar_api::Event::get_end() const'
calendar_sample_main.cc:(.text+0xaa8): undefined reference to `google_calendar_api::Event::get_end() const'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `googleapis::CalendarSample::Run()':
calendar_sample_main.cc:(.text+0x2a84): undefined reference to `google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x2b07): undefined reference to `google_calendar_api::Event::mutable_end()'
calendar_sample_main.cc:(.text+0x2ce8): undefined reference to `google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x2d6b): undefined reference to `google_calendar_api::Event::mutable_end()'
calendar_sample_main.cc:(.text+0x2f76): undefined reference to `google_calendar_api::Event::mutable_start()'
calendar_sample_main.cc:(.text+0x300d): undefined reference to `google_calendar_api::Event::mutable_end()'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `void googleapis::DisplayList<google_calendar_api::CalendarList, google_calendar_api::CalendarListEntry>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_calendar_api::CalendarList const&)':
calendar_sample_main.cc:(.text._ZN10googleapis11DisplayListIN19google_calendar_api12CalendarListENS1_17CalendarListEntryEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKT_[_ZN10googleapis11DisplayListIN19google_calendar_api12CalendarListENS1_17CalendarListEntryEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKT_]+0xdd): undefined reference to `google_calendar_api::CalendarList::get_items() const'
CMakeFiles/calendar_sample.dir/calendar_sample_main.cc.o: In function `void googleapis::DisplayList<google_calendar_api::Events, google_calendar_api::Event>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_calendar_api::Events const&)':
calendar_sample_main.cc:(.text._ZN10googleapis11DisplayListIN19google_calendar_api6EventsENS1_5EventEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKT_[_ZN10googleapis11DisplayListIN19google_calendar_api6EventsENS1_5EventEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKT_]+0xdd): undefined reference to `google_calendar_api::Events::get_items() const'
collect2: error: ld returned 1 exit status
src/samples/CMakeFiles/calendar_sample.dir/build.make:97: recipe for target 'bin/calendar_sample' failed
make[2]: *** [bin/calendar_sample] Error 1
CMakeFiles/Makefile2:817: recipe for target 'src/samples/CMakeFiles/calendar_sample.dir/all' failed
make[1]: *** [src/samples/CMakeFiles/calendar_sample.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by harshapat** [comment]
Events::get_items() api is not implemented. Thats the reason for this error.
May be JSonCpp library has got updated.

**Comment by SurferJeffAtGoogle** [comment]
Fixed.
