### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by asjgi** [google/google-api-cpp-client#28]
i have got a Big problem.

david@david-U460-MFLGL:~/workspace/copy/google-api-cpp-client/build$ ./bin/calendar_sample ./bin/client_secret.json ./bin/roots.pem 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0504 16:21:25.646176  7076 oauth2_authorization.cc:104] Invalid JSON
Could not initialize application.
Invalid JSON
david@david-U460-MFLGL:~/workspace/copy/google-api-cpp-client/build$ 

Anyone who Plz help ~

**Comment by SurferJeffAtGoogle** [comment]
Obsolete.
