### ISSUE TITLE
Can't build: struct mg_callbacks callbacks_; isn't defined 

### ISSUE THREAD

**Issue by iolalla** [google/google-api-cpp-client#29]
Finally after installing a few libraries by hand got compiling the code, but not this, cause this struct is undefined, looks like there is code pending to commit.
Thanks.

```
In file included from /home/iolalla/gcloud-cpp/src/samples/installed_application.cc:39:0:
/home/iolalla/gcloud-cpp/src/googleapis/client/util/mongoose_webserver.h:166:23: error: field ‘callbacks_’ has inco
mplete type ‘googleapis::client::mg_callbacks’
   struct mg_callbacks callbacks_;
                       ^
/home/iolalla/gcloud-cpp/src/googleapis/client/util/mongoose_webserver.h:166:10: note: forward declaration of ‘stru
ct googleapis::client::mg_callbacks’
   struct mg_callbacks callbacks_;
```

**Comment by asjgi** [comment]
This is not to build when i was last month
and i seen that webpage of google is not service of cpp client service

**Comment by harshapat** [comment]
You may have to download the older version of mongoose src.
Its available under [google/ion](https://github.com/google/ion/tree/master/third_party/mongoose)

**Comment by SurferJeffAtGoogle** [comment]
The build is now fixed.  The mongoose samples have been removed.
