### ISSUE TITLE
Calendar sample program does not work well, 

### ISSUE THREAD

**Issue by chxiaoxin** [google/google-api-cpp-client#30]
Compile and run the calendar sample program, but it comes with these output like below:

SAMPLE:  Getting User Authorization

Welcome to the Google APIs for C++ CalendarSample.
  You will need to authorize this program to look at your calendar.
  If you would like to save these credentials between runs
  (or restore from an earlier run) then enter a Google Email Address.
  Otherwise just press return.

  Address: 
Enter the following URL into a browser:
https://accounts.google.com/o/oauth2/auth?client_id=145956129682-b1pb20fote82gao680jt5r3fa9e71m4u.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&response_type=code

Enter the browser's response to confirm authorization: 4/9wprvnQF1rACiydJxH0xKBBp9mAT1FdpvYHqHQhumnU
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0722 11:01:33.061663 16563 curl_http_transport.cc:238] Using cacerts from /home/lixin/roots.pem
Authorized 

SAMPLE:  Showing Initial Calendars
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Adding Calendar
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Showing Updated Calendars
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Add Calendar Event
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Patch Calendar Event
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Update Calendar Event
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

Adding bulk events using a batch request
Error adding batched event 0
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 1
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 2
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 3
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 4
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 5
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 6
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 7
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 8
NOT_FOUND: Http(404) Not Found
Not Found
Error adding batched event 9
NOT_FOUND: Http(404) Not Found
Not Found
All Events

SAMPLE:  Deleting Calendar
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

SAMPLE:  Showing Final Calendars
====  ERROR  ====
Status: Http(404) Not Found
HTTP Status Code = 404

Not Found

Done!

Incredible a series of not found, I have not change any part of the program,

**Comment by SurferJeffAtGoogle** [comment]
Fixed.
