### ISSUE TITLE
Mac build fails if space in path

### ISSUE THREAD

**Issue by martin-gorner** [google/google-api-cpp-client#31]
prepare_dependencies.py script fails with the following message if there is a space in the current path:

```
  ---------------------------------------------
  Error when bootstrapping CMake:
  Cannot find appropriate Makefile processor on this system.
  Please specify one using environment variable MAKE.
  ---------------------------------------------
  Log of errors: <log file>"
  ---------------------------------------------
```

Digging into the log file the relevant error appears. It is due to a space in the current path.

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
