### ISSUE TITLE
Failure Building Clients for Other APIs

### ISSUE THREAD

**Issue by cramertj** [google/google-api-cpp-client#45]
Following the ["Building Clients for Other APIs" section of the README](https://github.com/google/google-api-cpp-client#building-clients-for-other-apis) results in an error:

```
➜  apis-client-generator git:(6b13208) python src/googleapis/codegen/generate_library.py \
--api_name=drive --api_version=v2 --language=cpp --output_dir=/tmp/generated               
FATAL Flags parsing error: flag --language=cpp: value should be one of <csharp|dart|gwt|java|php|python|sample>
Pass --helpshort or --helpfull to see help on flags.

```

**Comment by cramertj** [comment]
Running `./generate.sh` with the same flags works just fine. I'm imagining the README just needs an update.

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
