### ISSUE TITLE
First upload to GCS always times out

### ISSUE THREAD

**Issue by MitchRudominer** [google/google-api-cpp-client#48]
I am using the Google APIs Client library for C++ in order to upload files to a GCS bucket. In my experience the first attempt at an upload always fails with a timeout.
Subsequent upload attempts succeed. Also if I perform a different operation before the first upload, such as listing the buckets, then that succeeds and the
first upload after that succeeds. I only get the timeout if the first thing I do is an upload.

Here is the error I get:

Call to url=https://www.googleapis.com/upload/storage/v1/b/<MY_BUCKET_NAME_REDACTED>/o?uploadType=media&name=<MY_FILE_NAME_REDACTED> failed with http status 0
E1114 10:34:54.355522 18569 gcs_util.cc:113] Error attempting upload: DEADLINE_EXCEEDED: Request timed out

Does anyone have any insight into this issue? Below is a snippet of my code used to perform the upload:

  std::unique_ptr<ObjectsResource_InsertMethod> request(
      storage_service_->get_objects().NewInsertMethod(
          &oauth_credential_, bucket, nullptr, mime_type.c_str(),
          NewUnmanagedInMemoryDataReader(file_contents)));
  request->set_name(file_path);

  // Execute the request.
  Json::Value value;
  google_storage_api::Object response(&value);
  auto status = request->ExecuteAndParseResponse(&response);

I have attached two curl verbose logging output text files. The first one called
"upload-first-fails.txt" is the output from when I do the upload first and it fails.
The second one called "list-first-succeeds.txt" is the output from when I do a
list operation first and that succeeds.

[upload-first-fails.txt](https://github.com/google/google-api-cpp-client/files/1475655/upload-first-fails.txt)
[list-first-succeeds.txt](https://github.com/google/google-api-cpp-client/files/1475656/list-first-succeeds.txt)

**Comment by MitchRudominer** [comment]
I found another instance of this same phenomenon. If we make the substitution

GCS, upload ---> Bigquery InsertAll  (a mutation operation)
GCS, list buckets ---> Bigquery GetTable  (a fetch operation)

then exactly the same phenomenon occurs, namely If I do the fetch operation first it succeeds
and after that I can do the mutation operation. And If I do the mutation operation first it times-out
the first time but then succeeds on subsequent times.

So there seems to be something more general going on here.

**Comment by MitchRudominer** [comment]
I was able to fix this issue in my local copy of bigtable-api-cpp-client.
The problem turns out to be that when the server returns a 401 UNAUTHORIZED
and the client does the OAuth handshake, then after the handshake the client needs
to perform the upload again and in order to do that the client needs to reset the 
content reader and it is failing to do so.

Here is my fix:
On line 627 of //src/googleapis/client/transport/http_request.cc
in the method void AttemptToExecute(bool async)
I added 
 if (request_->content_reader_) {
      request_->content_reader_->Reset();
 }

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
