### ISSUE TITLE
undefined reference to `googleapis::client::New ....

### ISSUE THREAD

**Issue by rhymerjr** [google/google-api-cpp-client#49]
How can I solve it?

../google-api-cpp-client-master/build/lib/libgoogleapis_http.a(media_uploader.cc.o): In function `googleapis::client::MediaUploader::CreateMultipartPayloadReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
media_uploader.cc:(.text+0x1a15): undefined reference to `googleapis::client::NewCompositeReaderListAndContainerDeleter(std::vector<googleapis::client::DataReader*, std::allocator<googleapis::client::DataReader*> >*)'
media_uploader.cc:(.text+0x1a27): undefined reference to `googleapis::client::NewManagedCompositeDataReader(std::vector<googleapis::client::DataReader*, std::allocator<googleapis::client::DataReader*> > const&, googleapis::Closure*)'
../google-api-cpp-client-master/build/lib/libgoogleapis_http.a(http_request_batch.cc.o): In function `googleapis::client::HttpRequestBatch::PrepareFinalHttpRequest()':
http_request_batch.cc:(.text+0x27ce): undefined reference to `googleapis::client::NewCompositeReaderListAndContainerDeleter(std::vector<googleapis::client::DataReader*, std::allocator<googleapis::client::DataReader*> >*)'
http_request_batch.cc:(.text+0x27e3): undefined reference to `googleapis::client::NewManagedCompositeDataReader(std::vector<googleapis::client::DataReader*, std::allocator<googleapis::client::DataReader*> > const&, googleapis::Closure*)'
collect2: error: ld returned 1 exit status

They are really missing ?

My source:

#include <iostream>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <fstream>
#include <memory>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/data_reader.h"
#include "googleapis/client/service/media_uploader.h"
#include "googleapis/client/service/client_service.h"
#include "googleapis/client/data/data_reader.h"
#include "googleapis/client/transport/http_authorization.h"
#include "googleapis/client/transport/http_request.h"
#include "googleapis/client/transport/http_transport.h"
#include "googleapis/client/transport/curl_http_transport.h"
#include "googleapis/client/auth/file_credential_store.h"
#include "googleapis/client/auth/oauth2_authorization.h"
#include "googleapis/client/data/serializable_json.h"
#include "googleapis/client/util/status.h"
#include "googleapis/client/util/uri_utils.h"
#include "googleapis/strings/strcat.h"
#include "googleapis/strings/stringpiece.h"
#include "../google-api-cpp-client-master/service_apis/analytics/google/analytics_api/analytics_api.h"

using googleapis::client::HttpTransport;
using googleapis::client::HttpTransportLayerConfig;
using googleapis::client::OAuth2Credential;
//using googleapis::client::OAuth2ServiceAccountFlow;
#if HAVE_OPENSSL
using googleapis::client::OpenSslCodecFactory;
#endif
using googleapis::client::StatusInvalidArgument;

using googleapis::client::CredentialStore;
using googleapis::client::FileCredentialStoreFactory;
using googleapis::client::OAuth2AuthorizationFlow;
using googleapis::client::OAuth2Credential;
using googleapis::client::OAuth2RequestOptions;
using googleapis::client::HttpTransportOptions;
//using googleapis::client::HttpTransport;
using googleapis::client::HttpTransportFactory;
using googleapis::client::CurlHttpTransport;
using googleapis::client::CurlHttpTransportFactory;
using googleapis::client::DateTime;
using google_analytics_api::AnalyticsService;
using namespace std;

int main(int argc, char* argv[])
{
    google::InitGoogleLogging(argv[0]);
    google::ParseCommandLineFlags(&argc, &argv, true);
    google::InstallFailureSignalHandler();

    const std::string jsonFile("AnalyticsService-d724a72419b7.json");

    OAuth2Credential credential_;
    std::unique_ptr<AnalyticsService> analytics_;
    //std::unique_ptr<OAuth2ServiceAccountFlow> flow_;
    std::unique_ptr<OAuth2AuthorizationFlow> flow_;
    std::unique_ptr<HttpTransportLayerConfig> config_;
    googleapis::util::Status status;
    config_.reset(new HttpTransportLayerConfig);
    HttpTransportFactory* factory = new CurlHttpTransportFactory(config_.get());
    config_->ResetDefaultTransportFactory(factory);

    //flow_.reset(new OAuth2ServiceAccountFlow(config_->NewDefaultTransportOrDie()));
    flow_.reset(new OAuth2AuthorizationFlow(config_->NewDefaultTransportOrDie()));
    std::string json(std::istreambuf_iterator<char>(std::ifstream(jsonFile).rdbuf()),
                std::istreambuf_iterator<char>());

    flow_->InitFromJson(json);

    // --- NO BUILD ERROR WITH THIS
    flow_->set_default_scopes( "https://www.googleapis.com/auth/analytics.readonly" );

    // --- GOT ERROR ABOVE
    //flow_->set_default_scopes( google_analytics_api::AnalyticsService::SCOPES::ANALYTICS_READONLY );

    // --- GOT ERROR ABOVE
    analytics_.reset(new AnalyticsService(config_->NewDefaultTransportOrDie()));

    // --- GOT ERROR ABOVE
    //AnalyticsService* ga = new AnalyticsService(config_->NewDefaultTransportOrDie());

    if (!status.ok()) printf("status.ok() : ERROR - Could not initialize application.\n");
    else
    {
        printf("status.ok() : OK - Application succesfully initialized\n");
        //credential_.set_flow(flow_.get());
    }
    printf("Done\n");
    return 0;
}

**Comment by SurferJeffAtGoogle** [comment]
Getting everything to compile is very frustrating.  I wish there were an easier way.

I copied and pasted this code into the project, and after a few missteps, got everything to build without error.  See this commit:
https://github.com/SurferJeffAtGoogle/google-api-cpp-client/commit/05ee8bacd164a1f74732097f8945973afe54ee7a
