### ISSUE TITLE
compute API still on beta15

### ISSUE THREAD

**Issue by rcmaniac25** [google/google-api-cpp-client#5]
The links to the [service API](https://google-api-client-libraries.appspot.com/resources/api-libraries/download/compute/v1beta15/cpp) and [C++ docs](https://google-api-client-libraries.appspot.com/resources/api-libraries/documentation/compute/v1beta15/cpp/latest/) about the API return 404, and the actual service API [site](https://developers.google.com/compute/docs/reference/v1beta15) says it has been deprecated in favor of beta16.

**Comment by aiuto** [comment]
see https://github.com/google/google-api-cpp-client/issues/9#issuecomment-69103067 for details
