### ISSUE TITLE
Latest downloaded generated bigquery code is incompatible with latest framework code

### ISSUE THREAD

**Issue by MitchRudominer** [google/google-api-cpp-client#50]
I just downloaded the latest generated bigquery client C++ API from [here](https://developers.google.com/resources/api-libraries/download/bigquery/v2/cpp).
After unzipping, I look in the included descriptor.json and I see "timestamp": "2017-11-10 04:05" which makes me believe the code I downloaded was generated this November.

But the downloaded generated code appears to be incompatible with the latest google-api-cpp-client framework code from [this repo ](repo https://github.com/google/google-api-cpp-client)  even though the relevent files in this repo appear to have not changed in over two years.

One of the compilation errors I am seeing is that the framework is expecting to invoke a method called get_next_page_token() but the generated code for bigquery does not implement that method. I include the full compiler error below.

Full compiler error below:

In file included from /home/rudominer/cobalt/src/third_party/google-api-cpp-client/service_apis/bigquery/google/bigquery_api/bigquery_service.cc:24:
In file included from /home/rudominer/cobalt/src/third_party/google-api-cpp-client/service_apis/bigquery/./google/bigquery_api/bigquery_service.h:32:
/home/rudominer/cobalt/src/third_party/google-api-cpp-client/src/googleapis/client/service/service_request_pager.h:233:45: error: no member named 'get_next_page_token' in 'google_bigquery_api::GetQueryResultsResponse'
    set_next_page_token(page_data_storage_->get_next_page_token());
                        ~~~~~~~~~~~~~~~~~~  ^
/home/rudominer/cobalt/src/third_party/google-api-cpp-client/src/googleapis/client/service/service_request_pager.h:259:12: note: in instantiation of member function 'googleapis::client::ServiceRequestPager<google_bigquery_api::JobsResource_GetQueryResultsMethod, google_bigquery_api::GetQueryResultsResponse>::ExecuteNextPage' requested here
  explicit EncapsulatedServiceRequestPager(REQUEST* request)
           ^
/home/rudominer/cobalt/src/third_party/google-api-cpp-client/service_apis/bigquery/google/bigquery_api/bigquery_service.cc:1236:14: note: in instantiation of member function 'googleapis::client::EncapsulatedServiceRequestPager<google_bigquery_api::JobsResource_GetQueryResultsMethod, google_bigquery_api::GetQueryResultsResponse>::EncapsulatedServiceRequestPager' requested here
  return new client::EncapsulatedServiceRequestPager<JobsResource_GetQueryResultsMethod, GetQueryResultsResponse>(new JobsResource_GetQueryResultsMethod(service_, _credential_, project_id, job_id));
             ^

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
