### ISSUE TITLE
HAVE_UGO_PERMISSIONS and HAVE_FSTAT64 always fail

### ISSUE THREAD

**Issue by coderforlife** [google/google-api-cpp-client#53]
The tests for `HAVE_UGO_PERMISSIONS` and `HAVE_FSTAT64` in `introspect.cmake` always since the `check_cxx_source_compiles` attempts to link the program as an executable program and since there is no main it fails to fully link.

The solution to this problem is to add `int main(void) { }` after each of the current code fragments.

Additionally, the test for `HAVE_FSTAT64` is incorrect. You must specify the type as `struct stat64` and not just `stat64` at least on my setup (even in C++).

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
