### ISSUE TITLE
Tons of depreciation warnings during compile

### ISSUE THREAD

**Issue by coderforlife** [google/google-api-cpp-client#54]
During the compile there are several depreciation warnings. Most are related to the jsoncpp library.

The only one I see that is not related to the jsoncpp library is `readdir_r` in `src/googleapis/util/file.cc` which was deprecated in 2015... The solution is to use `readdir` instead as discussed on the [`readdir` man page](http://man7.org/linux/man-pages/man3/readdir_r.3.html).

Then in various other files uses the following jsoncpp types should be replaced:

 * `Json::Reader` replaced by `Json::CharReader` or `Json::CharReaderBuilder`
 * `Json::FastWriter`, `Json::StyledStreamWriter`, and `Json::StyledWriter` replaced by `Json::StreamWriterBuilder`
 * `Json::Writer` replaced by `Json::StreamWriter`

And the following jsoncpp methods should be replaced:

 * `removeMember` is used everywhere and should be replaced by using one of the methods that takes the end of the string since UTF-8 strings can have embedded nulls
 * `memberName`  should be replaced by `name()` for the same UTF-8 reason above
 * `getFormatedErrorMessages` is deprecated due to misspelling and should be `getFormattedErrorMessages` instead

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
