### ISSUE TITLE
More samples needed

### ISSUE THREAD

**Issue by hj-ca** [google/google-api-cpp-client#55]
Samples needed to upload, download, create and delete files. I can't find any API document. It seems to me I'll better call python from my CPP application until more CPP samples are available. I've used Azure storage and they have more samples and API documentation.

**Comment by ibsusu** [comment]
I would very much like to second this.  Would it be possible to please, please get samples for other items besides calendar and storage?  I would selfishly like to request a sample for Drive but I don't know how much that would help others.

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
