### ISSUE TITLE
std::cout missing #include <iostream>

### ISSUE THREAD

**Issue by asiplas** [google/google-api-cpp-client#59]
[src/samples/storage_sample_main.cc](https://github.com/google/google-api-cpp-client/blob/d0bbe169d81a50936ec5fcea4e6dbcfb97303f13/src/samples/storage_sample_main.cc#L133) does not `#include <iostream>`… compiler complains about no `cout` in `std`.

```
google-api-cpp-client/src/samples/storage_sample_main.cc: In member function ‘void googleapis::StorageSample::Run()’:
google-api-cpp-client/src/samples/storage_sample_main.cc:133:10: error: ‘cout’ is not a member of ‘std’ 
     std::cout << "Could not list buckets: " << status.error_message()          
          ^~~~`
```

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
