### ISSUE TITLE
Mutex::WaitWithTimeout is broken for second fractions

### ISSUE THREAD

**Issue by movingtarget** [google/google-api-cpp-client#7]
Current code:
    ts.tv_sec = tv.tv_sec + millis / 1000;
    ts.tv_nsec = millis % 1000;

Should be:
    ts.tv_sec = tv.tv_sec + millis / 1000;
    ts.tv_nsec = (millis % 1000)*1000000;

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
