### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by TurkeyMan** [google/google-api-cpp-client#8]
It's hard to write any serious application and not support Windows.
Specifically, I was hoping for a C++ Youtube API, so I can stream videos in my multimedia application.

**Comment by sbouchex** [comment]
+1

**Comment by k0105** [comment]
Same here. While I personally despise Windows due to privacy concerns, not supporting it is not an option. Any roadmap or rough estimate when Windows support will become available? That would be very helpful.

**Comment by aiuto** [comment]
Can you point to things that are specifically broken?

**Comment by Megalegacy98** [comment]
I agree. It would be great to have Windows support

**Comment by k0105** [comment]
Just for the record: For the time being I implemented my module in Java and simply call it from C++. Since this issue hasn't been solved in over 2 years I won't hold my breath.

**Comment by tmatsuo** [comment]
Thanks for filing the issue, but we deprecated this repository, so closing.
